In [45]:
import numpy as np

In [46]:
a=np.zeros(4)
print(a)
print(a.shape)

[0. 0. 0. 0.]
(4,)


In [47]:
# I give here as Parameter the shape of my matrix
# random.sample generates me random sample of 2x2
a = np.random.sample((2, 2))
print(a)
a.shape

[[0.44236513 0.04997798]
 [0.77390955 0.93782363]]


(2, 2)

In [48]:
a=np.arange(1,10,1,dtype=float)
# from,to,step,dtype
a

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [49]:
a=np.arange(4)
b=np.random.rand(4)
print(a,b)

[0 1 2 3] [0.5792328  0.53516563 0.80204309 0.24814448]


In [50]:
a=np.array([5,4,3,2])
b=np.array([5.,4.,3.,2.])
print(f"my array= {a} and the data type is {a.dtype}")
print(f"my array= {b} and the data type is {b.dtype}")

my array= [5 4 3 2] and the data type is int32
my array= [5. 4. 3. 2.] and the data type is float64


##### Operation on Vectors:

In [51]:
# Vector indexing operation on 1-D vectors
a=np.arange(10)
print(a)
print(a.shape)
print(a[3])
print(a[-1])

[0 1 2 3 4 5 6 7 8 9]
(10,)
3
9


In [52]:
a=np.array([1,2,3,4])
print(a)
b=-a
print(b)
c=np.sum(a)
print(c)
d=np.mean(a)
print(d)
f=a**2
print(f)

[1 2 3 4]
[-1 -2 -3 -4]
10
2.5
[ 1  4  9 16]


In [53]:
# Vector Vector element-wise operations
a=np.random.rand(6)
print(a)
b=np.random.rand(6)
print(b)
c=a+b
print(c)

[0.59096694 0.32950282 0.98797985 0.86846315 0.16452144 0.80277814]
[0.02503441 0.89766393 0.41783454 0.53671084 0.19721356 0.26810967]
[0.61600136 1.22716675 1.40581439 1.40517399 0.361735   1.07088782]


In [54]:
# Scalar Vector operations
a=np.array([1,2,3,4])
b=5*a
print(b)

[ 5 10 15 20]


##### Vector Vector dot product
The dot product is a mainstay of Linear Algebra and NumPy. This is an operation used extensively in this course and should be well understood. The dot product is shown below.

In [55]:
# Lets define a function that multiply two vectors together
def my_dot(a,b):
    """
    Compute the dot product of two vectors
    Args:
        a => np array : input vector 
        b => np array : input vector
    Returns:
        Result of dot Products of two vectors
    """
    x=0
    for i in range(a.shape[0]):
        x=x +a[i]*b[i]
    return x


In [56]:
a=np.array([1,2,3,4])
b=np.array([-1,4,3,2])
x=my_dot(a,b)
print(x)

24


In [57]:
# This operation using my build in function is expensive and take times
# Instead of this we do use the dot operation of numpy
print(np.dot(a,b))

24


##### Performance test:
Lets do compare in time execution

In [58]:
import time

In [59]:
np.random.seed(1)
a=np.random.rand(10000000)
b=np.random.rand(10000000)
tic=time.time()
c=np.dot(a,b)
toc=time.time()
# We multiply the the result with 1000 to convert from seconds to ms
print(f"Execution time using the dot function of numpy is {1000*(toc-tic):.4f} ms")

Execution time using the dot function of numpy is 5.1422 ms


In [60]:
tic=time.time()
c=my_dot(a,b)
toc=time.time()
# We multiply the the result with 1000 to convert from seconds to ms
print(f"Execution time using the my dot function of numpy is {1000*(toc-tic):.4f} ms")

Execution time using the my dot function of numpy is 1865.3212 ms


In [62]:
a=np.zeros((5))
b=np.zeros((1,5))
# Notice that 
print(a,b)

[0. 0. 0. 0. 0.] [[0. 0. 0. 0. 0.]]


In [64]:
# reshape()
a=np.arange(6)
print(a)
# -1 means as much rows as needed & 2 refers to columns
b=a.reshape(-1,2)
print(b)

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]


In [69]:
# How to access the element in the first line second col
# We have two avialable
print(b[0][1])
print(b[0,1])
# How to access the second row
print(b[1])

1
1
[2 3]


In [72]:
a=np.arange(20).reshape(-1,10)
print(a)
print(a[0])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[0 1 2 3 4 5 6 7 8 9]
